package com.aipet.brain.pixel.avatar.clips

import com.aipet.brain.pixel.avatar.model.PixelFrame64
import com.aipet.brain.pixel.avatar.model.PixelPalette

/**
 * Canonical 64×64 base eye template.
 *
 * Legend (DEFAULT_EYE_PALETTE):
 *   '.' = transparent/void
 *   'B' = dark background face fill
 *   'W' = eye sclera / white
 *   'P' = pupil dark
 *   'H' = highlight dot
 *   'A' = accent
 *
 * Both eyes are centered slightly above vertical midpoint.
 * Eye spacing: ~12px gap between eyes.
 * Each eye: 14w × 10h rounded rect shape with a 6×6 pupil and 2×2 highlight.
 *
 * This template defines EYES_OPEN (full sclera visible, centered pupil).
 * All other states derive from this layout.
 */
object BaseEyeTemplate {

    // Row indices for eye region (within 64 rows)
    // Eye top at row 22, eye bottom at row 31 (10 px tall)
    // Left eye X: cols 10–23 (14 px wide)
    // Right eye X: cols 36–49 (14 px wide)

    val EYES_OPEN: PixelFrame64 = buildFrame {
        row(0,  21, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        // Eye row 0 (top): sclera outline
        row(22, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(23, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        // Eye row 2: pupil zone starts
        row(24, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(25, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        // Eye row 4: pupil with highlight
        row(26, "BBBBBBBBBB.WWWPPHPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPHHPWWW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        // Eye row 6-7
        row(28, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        // Eye bottom row
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    val EYES_HALF_OPEN: PixelFrame64 = buildFrame {
        row(0,  24, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        // Half-open: top 3 rows of sclera replaced by background (eyelid dropped)
        row(25, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(26, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    val EYES_CLOSED: PixelFrame64 = buildFrame {
        row(0, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    /** Eyes open but pupils shifted slightly left */
    val EYES_GLANCE_LEFT: PixelFrame64 = buildFrame {
        row(0,  21, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(22, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(23, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(24, "BBBBBBBBBB.WPPPPPPWWWWWWW.BBBBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBB")
        row(25, "BBBBBBBBBB.WPPPPPPWWWWWWW.BBBBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBB")
        row(26, "BBBBBBBBBB.WPPHPPPWWWWWWW.BBBBBBBBBBBB.WWWPPPHHPWWWWW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WPPPPPPWWWWWWW.BBBBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    /** Eyes open but pupils shifted slightly right */
    val EYES_GLANCE_RIGHT: PixelFrame64 = buildFrame {
        row(0,  21, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(22, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(23, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(24, "BBBBBBBBBB.WWWWWWPPPPPPPW.BBBBBBBBBBBB.WWWWWWWPPPPPPW.BBBBBBBBBB")
        row(25, "BBBBBBBBBB.WWWWWWPPPPPPPW.BBBBBBBBBBBB.WWWWWWWPPPPPPW.BBBBBBBBBB")
        row(26, "BBBBBBBBBB.WWWWWWPPPHHPPW.BBBBBBBBBBBB.WWWWWWWPPHPPPW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WWWWWWPPPPPPPW.BBBBBBBBBBBB.WWWWWWWPPPPPPW.BBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    /** Happy squint: eyes curved down-and-in (shorter vertical, wider bottom curve) */
    val EYES_HAPPY_SQUINT: PixelFrame64 = buildFrame {
        row(0,  23, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(24, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(25, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(26, "BBBBBBBBBB.WWWPPHPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPHHPWWW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    /** Sleepy drooped: eyelid covers top ~60% of eye */
    val EYES_SLEEPY_DROOP: PixelFrame64 = buildFrame {
        row(0,  27, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }

    /** Thinking squint: asymmetric — left eye slightly lower than right */
    val EYES_THINKING_SQUINT: PixelFrame64 = buildFrame {
        row(0,  22, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        // Left eye starts 2 rows lower than right
        row(23, "BBBBBBBBBBBBBBBBBBBBBBBBBB.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(24, "BBBBBBBBBBBBBBBBBBBBBBBBBB.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(25, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(26, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPHHPWWW.BBBBBBBBBB")
        row(27, "BBBBBBBBBB.WWWPPHPPPWWWWW.BBBBBBBBBBBB.WWWWWPPPPPPWWW.BBBBBBBBBB")
        row(28, "BBBBBBBBBB.WWWPPPPPPWWWWW.BBBBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBB")
        row(29, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBB.BBBBBBBBBBBBBB.BBBBBBBBBB")
        row(30, "BBBBBBBBBB.WWWWWWWWWWWWWW.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(31, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
        row(32, 63, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
    }
}

// ---------- DSL helpers for readable frame construction ----------

private class FrameBuilder {
    private val rows = MutableList(64) { "B".repeat(64) }

    fun row(index: Int, content: String) {
        if (index in 0..63) rows[index] = content.padEnd(64, 'B').take(64)
    }

    fun row(from: Int, to: Int, content: String) {
        for (i in from..to.coerceAtMost(63)) rows[i] = content.padEnd(64, 'B').take(64)
    }

    fun build(): PixelFrame64 = PixelFrame64(rows.toList())
}

private fun buildFrame(block: FrameBuilder.() -> Unit): PixelFrame64 =
    FrameBuilder().apply(block).build()
